# yaml-language-server: $schema=https://taskfile.dev/schema.json
# ---
# Docs:
# https://taskfile.dev/
# https://taskfile.dev/docs/reference/schema
version: "3"

vars:
  DEBUG: false

tasks:
  all:
    desc: "Run the whole recipe workflow"
    cmds:
      - cmd: mkdir -p target/
      - task: build-sample-app

  clean:
    desc: Clean up artifacts
    cmds:
      - cmd: git clean -fdx target/

  build-sample-app:
    desc: Build the sample application
    sources:
      - "src/*.c"
    generates:
      - "target/app.bin"
    cmds:
      - cmd: gcc -Wall -Werror  -ldl  -o target/app.bin  src/fake-app.c
      - cmd: ./target/app.bin

# eof
