# yaml-language-server: $schema=https://taskfile.dev/schema.json
# ---
# Docs:
# https://taskfile.dev/
# https://taskfile.dev/docs/reference/schema
version: "3"

vars:
  DEBUG: false

tasks:
  default:
    silent: true
    cmd: |
      echo "List all available tests with:"
      echo "[$] task --list-all"

# eof
